// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LeHaiDang214.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20211217082428_Create_Table_LHD0214")]
    partial class Create_Table_LHD0214
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("LeHaiDang214.Models.LHD0214", b =>
                {
                    b.Property<string>("LHDID")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("LHDGender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LHDName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("LHDID");

                    b.ToTable("LHD0214s");
                });

            modelBuilder.Entity("LeHaiDang214.Models.UniversityLHD214", b =>
                {
                    b.Property<string>("UniversityId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("UniversityName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("UniversityId");

                    b.ToTable("UniversityLHD214s");
                });
#pragma warning restore 612, 618
        }
    }
}
